services:
  dash:
    image: ginloy/fyp
    build: ./.
    restart: unless-stopped
    labels:
      caddy: https://fyp2.ginloy.com
      caddy.reverse_proxy: "{{upstreams http 8050}}"
    networks:
      - caddy
networks:
  caddy:
    external: true
